[package]
name = "ysqd"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5"
ctrlc = "3.4"
winreg = "0.50"

[build-dependencies]
winres = "0.1"
